obj-y := ctx_sw.o intc.o misc.o process.o ptrace.o reset.o setup.o traps.o \
	troubleshoot.o irq.o stacktrace.o sys.o

# these should be removed
obj-${CONFIG_WASM32_WEB_KBD} += kbd.o
obj-y += evt.o uio.o syscall.o stdio/
