#undef A_AFTER_CMD
#undef A_AFTER_DATA_IN
#undef A_AFTER_DATA_OUT
#undef A_AFTER_SELECTION
#undef A_AFTER_STATUS
#undef A_BEFORE_CMD
#undef A_COMMAND_COMPLETE_MSG
#undef A_COMPLETED_SELECTION_AS_TARGET
#undef A_CommandAddress
#undef A_CommandCount
#undef A_DATA_IN_AFTER_DATA_IN
#undef A_DEBUG_INTERRUPT
#undef A_DEBUG_INTERRUPT1
#undef A_DEBUG_INTERRUPT2
#undef A_DEBUG_INTERRUPT3
#undef A_DEBUG_INTERRUPT4
#undef A_DEBUG_INTERRUPT5
#undef A_DEBUG_INTERRUPT6
#undef A_DISCONNECT
#undef A_DISCONNECT_AFTER_CMD
#undef A_DISCONNECT_AFTER_DATA
#undef A_DISCONNECT_DURING_DATA
#undef A_DISCONNECT_MSG
#undef A_DURING_DATA_IN
#undef A_Device_ID
#undef A_EXTENDED_MSG
#undef A_FATAL
#undef A_FATAL_ILLEGAL_MSG_LENGTH
#undef A_FATAL_NOT_MSG_IN_AFTER_SELECTION
#undef A_FATAL_SEND_MSG
#undef A_FATAL_UNEXPECTED_RESELECTION_MSG
#undef A_GOOD_STATUS
#undef A_GOOD_STATUS_AFTER_STATUS
#undef A_IDENTIFY_MSG
#undef A_IDENTIFY_MSG_MASK
#undef A_MSG_IN
#undef A_MSG_IN_AFTER_CMD
#undef A_MSG_IN_AFTER_DATA_IN
#undef A_MSG_IN_AFTER_DATA_OUT
#undef A_MSG_IN_AFTER_STATUS
#undef A_MSG_IN_BEFORE_CMD
#undef A_MSG_IN_DURING_DATA_IN
#undef A_MSG_OUT
#undef A_MSG_OUT_AFTER_DATA_IN
#undef A_MessageCount
#undef A_MessageLocation
#undef A_NOT_MSG_IN
#undef A_NOT_MSG_IN_AFTER_STATUS
#undef A_NOT_MSG_OUT
#undef A_NOT_MSG_OUT_AFTER_SELECTION
#undef A_PARITY_ERROR_MSG
#undef A_REJECT_MSG
#undef A_REJECT_MSG_BEFORE_CMD
#undef A_REJECT_MSG_R
#undef A_RESELECTED_DURING_SELECTION
#undef A_RESELECTION_IDENTIFIED
#undef A_RESTORE_DATA_PTRS_MSG
#undef A_ReceiveMsgAddress
#undef A_SAVE_DATA_PTRS_MSG
#undef A_SDTR_MSG
#undef A_SDTR_MSG_AFTER_CMD
#undef A_SDTR_MSG_BEFORE_CMD
#undef A_SDTR_MSG_R
#undef A_SGScriptStartAddress
#undef A_SIMPLE_TAG_MSG
#undef A_StatusAddress
#undef A_TWO_BYTE_MSG
#undef A_TWO_BYTE_MSG_MASK
#undef A_UNEXPECTED_MSG
#undef A_UNEXPECTED_MSG_BEFORE_CMD
#undef A_UNEXPECTED_PHASE
#undef A_UNEXPECTED_PHASE_AFTER_CMD
#undef A_UNEXPECTED_PHASE_AFTER_DATA_IN
#undef A_UNEXPECTED_PHASE_AFTER_DATA_OUT
#undef A_UNEXPECTED_PHASE_BEFORE_CMD
#undef A_WDTR_MSG
#undef A_WDTR_MSG_AFTER_CMD
#undef A_WDTR_MSG_R
#undef Ent_Disconnect1
#undef Ent_Disconnect2
#undef Ent_Disconnect3
#undef Ent_Disconnect4
#undef Ent_Disconnect5
#undef Ent_Disconnect6
#undef Ent_Disconnect7
#undef Ent_Disconnect8
#undef Ent_Finish1
#undef Ent_Finish2
#undef Ent_FinishCommandComplete
#undef Ent_GetReselectionData
#undef Ent_GetReselectionWithTag
#undef Ent_IgnoreMessage
#undef Ent_MsgInDuringData
#undef Ent_ReceiveMessage
#undef Ent_SelectedAsTarget
#undef Ent_SendCommand
#undef Ent_SendMessage
#undef Ent_SendMessagePhaseMismatch
#undef Ent_SendMessageWithATN
#undef Ent_StartUp
